
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_PBL_CILAN_20 2
#define PARTNER_PBL_CHILI_20 3
#define PARTNER_PBL_CRESS_20 4
#define PARTNER_PBL_LEAF_27 5
#define PARTNER_PBL_WALLY_27 6
#define PARTNER_PBL_SERENA_27 7
#define PARTNER_PBL_LEAF_30 8
#define PARTNER_PBL_WALLY_30 9
#define PARTNER_PBL_SERENA_30 10
#define PARTNER_COUNT 11

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
