
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_PBL_CILAN_BOSS_20 2
#define PARTNER_PBL_CHILI_BOSS_20 3
#define PARTNER_PBL_CRESS_BOSS_20 4
#define PARTNER_COUNT 5

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
