#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

#define BERRY_FIRMNESS_UNKNOWN     0
#define BERRY_FIRMNESS_VERY_SOFT   1
#define BERRY_FIRMNESS_SOFT        2
#define BERRY_FIRMNESS_HARD        3
#define BERRY_FIRMNESS_VERY_HARD   4
#define BERRY_FIRMNESS_SUPER_HARD  5

#define BERRY_COLOR_RED    0
#define BERRY_COLOR_BLUE   1
#define BERRY_COLOR_PURPLE 2
#define BERRY_COLOR_GREEN  3
#define BERRY_COLOR_YELLOW 4
#define BERRY_COLOR_PINK   5

#define FLAVOR_SPICY   0
#define FLAVOR_DRY     1
#define FLAVOR_SWEET   2
#define FLAVOR_BITTER  3
#define FLAVOR_SOUR    4
#define FLAVOR_COUNT   5

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_TRUNK       6 // These follow BERRY_STAGE_BERRIES to preserve save compatibility
#define BERRY_STAGE_BUDDING     7
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"
#define BERRY_TREE_ROUTE_102_PECHA   0
#define BERRY_TREE_ROUTE_102_ORAN    0
#define BERRY_TREE_ROUTE_104_SOIL_1  0
#define BERRY_TREE_ROUTE_104_ORAN_1  0
#define BERRY_TREE_ROUTE_103_CHERI_1 0
#define BERRY_TREE_ROUTE_103_LEPPA   0
#define BERRY_TREE_ROUTE_103_CHERI_2 0
#define BERRY_TREE_ROUTE_104_CHERI_1 0
#define BERRY_TREE_ROUTE_104_SOIL_2  0
#define BERRY_TREE_ROUTE_104_LEPPA    0
#define BERRY_TREE_ROUTE_104_ORAN_2   0
#define BERRY_TREE_ROUTE_104_SOIL_3   0
#define BERRY_TREE_ROUTE_104_PECHA    0
#define BERRY_TREE_ROUTE_123_QUALOT_1 0
#define BERRY_TREE_ROUTE_123_POMEG_1  0
#define BERRY_TREE_ROUTE_110_NANAB_1  0
#define BERRY_TREE_ROUTE_110_NANAB_2  0
#define BERRY_TREE_ROUTE_110_NANAB_3  0
#define BERRY_TREE_ROUTE_111_RAZZ_1   0
#define BERRY_TREE_ROUTE_111_RAZZ_2   0
#define BERRY_TREE_ROUTE_112_RAWST_1  0
#define BERRY_TREE_ROUTE_112_PECHA_1  0
#define BERRY_TREE_ROUTE_112_PECHA_2  0
#define BERRY_TREE_ROUTE_112_RAWST_2  0
#define BERRY_TREE_ROUTE_116_PINAP_1  0
#define BERRY_TREE_ROUTE_116_CHESTO_1 0
#define BERRY_TREE_ROUTE_117_WEPEAR_1 0
#define BERRY_TREE_ROUTE_117_WEPEAR_2 0
#define BERRY_TREE_ROUTE_117_WEPEAR_3 0
#define BERRY_TREE_ROUTE_123_POMEG_2  0
#define BERRY_TREE_ROUTE_118_SITRUS_1 0
#define BERRY_TREE_ROUTE_118_SOIL     0
#define BERRY_TREE_ROUTE_118_SITRUS_2 0
#define BERRY_TREE_ROUTE_119_POMEG_1  0
#define BERRY_TREE_ROUTE_119_POMEG_2  0
#define BERRY_TREE_ROUTE_119_POMEG_3  0
#define BERRY_TREE_ROUTE_120_ASPEAR_1 0
#define BERRY_TREE_ROUTE_120_ASPEAR_2 0
#define BERRY_TREE_ROUTE_120_ASPEAR_3 0
#define BERRY_TREE_ROUTE_120_PECHA_1  0
#define BERRY_TREE_ROUTE_120_PECHA_2  0
#define BERRY_TREE_ROUTE_120_PECHA_3  0
#define BERRY_TREE_ROUTE_120_RAZZ     0
#define BERRY_TREE_ROUTE_120_NANAB    0
#define BERRY_TREE_ROUTE_120_PINAP    0
#define BERRY_TREE_ROUTE_120_WEPEAR   0
#define BERRY_TREE_ROUTE_121_PERSIM   0
#define BERRY_TREE_ROUTE_121_ASPEAR   0
#define BERRY_TREE_ROUTE_121_RAWST    0
#define BERRY_TREE_ROUTE_121_CHESTO   0
#define BERRY_TREE_ROUTE_121_SOIL_1   0
#define BERRY_TREE_ROUTE_121_NANAB_1  0
#define BERRY_TREE_ROUTE_121_NANAB_2  0
#define BERRY_TREE_ROUTE_121_SOIL_2   0
#define BERRY_TREE_ROUTE_115_BLUK_1   0
#define BERRY_TREE_ROUTE_115_BLUK_2   0
#define BERRY_TREE_UNUSED             0
#define BERRY_TREE_ROUTE_123_POMEG_3  0
#define BERRY_TREE_ROUTE_123_POMEG_4  0
#define BERRY_TREE_ROUTE_123_GREPA_1  0
#define BERRY_TREE_ROUTE_123_GREPA_2  0
#define BERRY_TREE_ROUTE_123_LEPPA_1  0
#define BERRY_TREE_ROUTE_123_SOIL     0
#define BERRY_TREE_ROUTE_123_LEPPA_2  0
#define BERRY_TREE_ROUTE_123_GREPA_3  0
#define BERRY_TREE_ROUTE_116_CHESTO_2 0
#define BERRY_TREE_ROUTE_116_PINAP_2  0
#define BERRY_TREE_ROUTE_114_PERSIM_1 0
#define BERRY_TREE_ROUTE_115_KELPSY_1 0
#define BERRY_TREE_ROUTE_115_KELPSY_2 0
#define BERRY_TREE_ROUTE_115_KELPSY_3 0
#define BERRY_TREE_ROUTE_123_GREPA_4  0
#define BERRY_TREE_ROUTE_123_QUALOT_2 0
#define BERRY_TREE_ROUTE_123_QUALOT_3 0
#define BERRY_TREE_ROUTE_104_SOIL_4   0
#define BERRY_TREE_ROUTE_104_CHERI_2  0
#define BERRY_TREE_ROUTE_114_PERSIM_2 0
#define BERRY_TREE_ROUTE_114_PERSIM_3 0
#define BERRY_TREE_ROUTE_123_QUALOT_4 0
#define BERRY_TREE_ROUTE_111_ORAN_1   0
#define BERRY_TREE_ROUTE_111_ORAN_2   0
#define BERRY_TREE_ROUTE_130_LIECHI   0
#define BERRY_TREE_ROUTE_119_HONDEW_1 0
#define BERRY_TREE_ROUTE_119_HONDEW_2 0
#define BERRY_TREE_ROUTE_119_SITRUS   0
#define BERRY_TREE_ROUTE_119_LEPPA    0
#define BERRY_TREE_ROUTE_123_PECHA    0
#define BERRY_TREE_ROUTE_123_SITRUS   0
#define BERRY_TREE_ROUTE_123_RAWST    0

// Remainder are unused

#define BERRY_TREES_COUNT 12

#endif // GUARD_CONSTANTS_BERRY_H
