#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(WORK_UP) \
    F(DRAGON_CLAW) \
    F(PSYSHOCK) \
    F(CALM_MIND) \
    F(BUG_BITE) \
    F(TOXIC) \
    F(SNOWSCAPE) \
    F(BULK_UP) \
    F(VENOSHOCK) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(TRAILBLAZE) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(HYPER_VOICE) \
    F(ICY_WIND) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(FLIP_TURN) \
    F(REFLECT) \
    F(SLUDGE_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(LEECH_LIFE) \
    F(FACADE) \
    F(FLAME_CHARGE) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(AGILITY) \
    F(WEATHER_BALL) \
    F(DRAINING_KISS) \
    F(OVERHEAT) \
    F(ROOST) \
    F(FOCUS_BLAST) \
    F(ENERGY_BALL) \
    F(FALSE_SWIPE) \
    F(SCALD) \
    F(FLING) \
    F(CHARGE_BEAM) \
    F(BODY_PRESS) \
    F(DRAGON_PULSE) \
    F(DRAIN_PUNCH) \
    F(WILL_O_WISP) \
    F(ACROBATICS) \
    F(NASTY_PLOT) \
    F(EXPLOSION) \
    F(SHADOW_CLAW) \
    F(AURA_SPHERE) \
    F(SMART_STRIKE) \
    F(CLOSE_COMBAT) \
    F(ROCK_POLISH) \
    F(AURORA_VEIL) \
    F(STONE_EDGE) \
    F(VOLT_SWITCH) \
    F(THUNDER_WAVE) \
    F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(FLY) \
    F(HEX) \
    F(BULLDOZE) \
    F(TRIPLE_AXEL) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(PLUCK) \
    F(NATURAL_GIFT) \
    F(POISON_JAB) \
    F(HURRICANE) \
    F(GRASS_KNOT) \
    F(SWAGGER) \
    F(SLEEP_TALK) \
    F(U_TURN) \
    F(SUBSTITUTE) \
    F(FLASH_CANNON) \
    F(TRICK_ROOM) \
    F(WILD_CHARGE) \
    F(DEFOG) \
    F(SNARL) \
    F(DRACO_METEOR) \
    F(DARK_PULSE) \
    F(POWER_UP_PUNCH) \
    F(DAZZLING_GLEAM) \
    F(TERA_BLAST)

#define FOREACH_HM(F) \
    F(CUT) \
    F(ROCK_CLIMB) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
