#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     5
#define HIDDEN_WILD_COUNT   5
#define SELECTED_LAND_WILD_COUNT     6
#define SELECTED_WATER_WILD_COUNT    3
#define SELECTED_ROCK_WILD_COUNT     SELECTED_WATER_WILD_COUNT
#define SELECTED_FISH_WILD_COUNT     SELECTED_WATER_WILD_COUNT
#define SELECTED_HIDDEN_WILD_COUNT   3

#define NUM_ALTERING_CAVE_TABLES 9

#define FISHING_CHAIN_LENGTH_MAX 200
#define FISHING_CHAIN_SHINY_STREAK_MAX 20

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
