Zone9F_MapScripts::
	.byte 0


Zone9F_EventScript_Ari::
# 4 "data/maps/Zone9F/scripts.pory"
	lock
# 5 "data/maps/Zone9F/scripts.pory"
	faceplayer
# 6 "data/maps/Zone9F/scripts.pory"
	msgbox Zone9F_EventScript_Ari_Text_0
# 7 "data/maps/Zone9F/scripts.pory"
	release
	end


Zone9F_EventScript_Bertha::
# 12 "data/maps/Zone9F/scripts.pory"
	lock
# 13 "data/maps/Zone9F/scripts.pory"
	faceplayer
# 14 "data/maps/Zone9F/scripts.pory"
	msgbox Zone9F_EventScript_Bertha_Text_0
# 15 "data/maps/Zone9F/scripts.pory"
	release
	end


Zone9F_EventScript_Cassandra::
# 20 "data/maps/Zone9F/scripts.pory"
	lock
# 21 "data/maps/Zone9F/scripts.pory"
	faceplayer
# 22 "data/maps/Zone9F/scripts.pory"
	msgbox Zone9F_EventScript_Cassandra_Text_0
# 23 "data/maps/Zone9F/scripts.pory"
	release
	end


Zone9F_EventScript_Dominic::
# 28 "data/maps/Zone9F/scripts.pory"
	lock
# 29 "data/maps/Zone9F/scripts.pory"
	faceplayer
# 30 "data/maps/Zone9F/scripts.pory"
	msgbox Zone9F_EventScript_Dominic_Text_0
# 31 "data/maps/Zone9F/scripts.pory"
	release
	end


Zone9F_EventScript_Erica::
# 36 "data/maps/Zone9F/scripts.pory"
	lock
# 37 "data/maps/Zone9F/scripts.pory"
	faceplayer
# 38 "data/maps/Zone9F/scripts.pory"
	msgbox Zone9F_EventScript_Erica_Text_0
# 39 "data/maps/Zone9F/scripts.pory"
	release
	end


Zone9F_EventScript_Ari_Text_0:
# 6 "data/maps/Zone9F/scripts.pory"
	.string "{COLOR BLUE}Ari{COLOR DARK_GRAY}: I miss my cousin Victoria. She lives\n"
	.string "in the Hoenn region.$"

Zone9F_EventScript_Bertha_Text_0:
# 14 "data/maps/Zone9F/scripts.pory"
	.string "{COLOR BLUE}Bertha{COLOR DARK_GRAY}: Why did Mom buy this house?\n"
	.string "It's so small for the five of us…$"

Zone9F_EventScript_Cassandra_Text_0:
# 22 "data/maps/Zone9F/scripts.pory"
	.string "{COLOR BLUE}Cassandra{COLOR DARK_GRAY}: All my kids do is complain,\n"
	.string "complain, then complain some more.$"

Zone9F_EventScript_Dominic_Text_0:
# 30 "data/maps/Zone9F/scripts.pory"
	.string "{COLOR BLUE}Dominic{COLOR DARK_GRAY}: I wonder what's for dinner…$"

Zone9F_EventScript_Erica_Text_0:
# 38 "data/maps/Zone9F/scripts.pory"
	.string "{COLOR BLUE}Erica{COLOR DARK_GRAY}: May your travels be safe.$"
