# 1 "data/text/battle_labyrinth.pory"

# 2 "data/text/battle_labyrinth.pory"

# 3 "data/text/battle_labyrinth.pory"
gText_Colress_UpgradedWarp:
# 4 "data/text/battle_labyrinth.pory"
	.string "Because of your progress,\n"
# 5 "data/text/battle_labyrinth.pory"
	.string "you have unlocked a special warp in\l"
# 6 "data/text/battle_labyrinth.pory"
	.string "Zone 0.$"
# 7 "data/text/battle_labyrinth.pory"

# 8 "data/text/battle_labyrinth.pory"
gText_Lelouch_ExpTrainingFinished:
# 9 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: The training session has\n"
# 10 "data/text/battle_labyrinth.pory"
	.string "finished.\p"
# 11 "data/text/battle_labyrinth.pory"
	.string "Your Pokémon has grown stronger.$"
# 12 "data/text/battle_labyrinth.pory"

# 13 "data/text/battle_labyrinth.pory"
gText_Lelouch_DidNotTrain:
# 14 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: If you do want to\n"
# 15 "data/text/battle_labyrinth.pory"
	.string "train your Pokémon, I'll be here.$"
# 16 "data/text/battle_labyrinth.pory"

# 17 "data/text/battle_labyrinth.pory"
gText_Lelouch_Exp:
# 18 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: With Experience Training,\n"
# 19 "data/text/battle_labyrinth.pory"
	.string "you can train one Pokémon to any\l"
# 20 "data/text/battle_labyrinth.pory"
	.string "level up to the level cap,\l"
# 21 "data/text/battle_labyrinth.pory"
	.string "at the cost of one Red Shard.\p"
# 22 "data/text/battle_labyrinth.pory"
	.string "Would you like to start an\n"
# 23 "data/text/battle_labyrinth.pory"
	.string "Experience Training session?$"
# 24 "data/text/battle_labyrinth.pory"

# 25 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayRed:
# 26 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Red Shard.$"
# 27 "data/text/battle_labyrinth.pory"

# 28 "data/text/battle_labyrinth.pory"
gText_Lelouch_ChooseTraining:
# 29 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Choose which training\n"
# 30 "data/text/battle_labyrinth.pory"
	.string "regiment you would like.$"
# 31 "data/text/battle_labyrinth.pory"

# 32 "data/text/battle_labyrinth.pory"
gText_Lelouch_CostsBlueShards:
# 33 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Move Reminder services\n"
# 34 "data/text/battle_labyrinth.pory"
	.string "cost one Blue Shard.\p"
# 35 "data/text/battle_labyrinth.pory"
	.string "Would you like me to teach a\n"
# 36 "data/text/battle_labyrinth.pory"
	.string "forgotten move to your Pokémon?$"
# 37 "data/text/battle_labyrinth.pory"

# 38 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayBlue:
# 39 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Blue Shard.$"
# 40 "data/text/battle_labyrinth.pory"

# 41 "data/text/battle_labyrinth.pory"
gText_Lelouch_CostsYellowShards:
# 42 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Move Tutor services cost\n"
# 43 "data/text/battle_labyrinth.pory"
	.string "Yellow Shards. Which move would you\l"
# 44 "data/text/battle_labyrinth.pory"
	.string "like to tutor?$"
# 45 "data/text/battle_labyrinth.pory"

# 46 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayYellow1:
# 47 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Yellow Shard.$"
# 48 "data/text/battle_labyrinth.pory"

# 49 "data/text/battle_labyrinth.pory"
gText_Lelouch_CostsGreenShards:
# 50 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: I can craft special items\n"
# 51 "data/text/battle_labyrinth.pory"
	.string "as well as upgrade your items\l"
# 52 "data/text/battle_labyrinth.pory"
	.string "in exchange for Green Shards.\l"
# 53 "data/text/battle_labyrinth.pory"
	.string "What would you like?$"
# 54 "data/text/battle_labyrinth.pory"

# 55 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayGreen:
# 56 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Green Shard.$"
# 57 "data/text/battle_labyrinth.pory"

# 58 "data/text/battle_labyrinth.pory"
gText_HealingSign:
# 59 "data/text/battle_labyrinth.pory"
	.string "Joy's Healing Shop\n"
# 60 "data/text/battle_labyrinth.pory"
	.string "Health care costs money!$"
# 61 "data/text/battle_labyrinth.pory"

# 62 "data/text/battle_labyrinth.pory"
gText_ExitSign:
# 63 "data/text/battle_labyrinth.pory"
	.string "This is the exit!$"
# 64 "data/text/battle_labyrinth.pory"

# 65 "data/text/battle_labyrinth.pory"
gText_NotEnoughMons:
# 66 "data/text/battle_labyrinth.pory"
	.string "You need at least two Pokémon to\n"
# 67 "data/text/battle_labyrinth.pory"
	.string "initiate a Double Battle.$"
# 68 "data/text/battle_labyrinth.pory"

# 69 "data/text/battle_labyrinth.pory"
gText_PleasePick3Mons:
# 70 "data/text/battle_labyrinth.pory"
	.string "Please select three Pokémon to\n"
# 71 "data/text/battle_labyrinth.pory"
	.string "participate in the tag battle.$"
