# 67 "data/text/battle_labyrinth.pory"

# 68 "data/text/battle_labyrinth.pory"

# 69 "data/text/battle_labyrinth.pory"
gText_Colress_UpgradedWarp:
# 70 "data/text/battle_labyrinth.pory"
	.string "Because of your progress,\n"
# 71 "data/text/battle_labyrinth.pory"
	.string "you have unlocked a special warp in\l"
# 72 "data/text/battle_labyrinth.pory"
	.string "Zone 0.$"
# 73 "data/text/battle_labyrinth.pory"

# 74 "data/text/battle_labyrinth.pory"
gText_Lelouch_ExpTrainingFinished:
# 75 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: The training session has\n"
# 76 "data/text/battle_labyrinth.pory"
	.string "finished.\p"
# 77 "data/text/battle_labyrinth.pory"
	.string "Your Pokémon has grown stronger.$"
# 78 "data/text/battle_labyrinth.pory"

# 79 "data/text/battle_labyrinth.pory"
gText_Lelouch_DidNotTrain:
# 80 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: If you do want to\n"
# 81 "data/text/battle_labyrinth.pory"
	.string "train your Pokémon, I'll be here.$"
# 82 "data/text/battle_labyrinth.pory"

# 83 "data/text/battle_labyrinth.pory"
gText_Lelouch_Exp:
# 84 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: With Experience Training,\n"
# 85 "data/text/battle_labyrinth.pory"
	.string "you can train one Pokémon to any\l"
# 86 "data/text/battle_labyrinth.pory"
	.string "level up to the level cap,\l"
# 87 "data/text/battle_labyrinth.pory"
	.string "at the cost of one Red Shard.\p"
# 88 "data/text/battle_labyrinth.pory"
	.string "Would you like to start an\n"
# 89 "data/text/battle_labyrinth.pory"
	.string "Experience Training session?$"
# 90 "data/text/battle_labyrinth.pory"

# 91 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayRed:
# 92 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Red Shard.$"
# 93 "data/text/battle_labyrinth.pory"

# 94 "data/text/battle_labyrinth.pory"
gText_Lelouch_ChooseTraining:
# 95 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Choose which training\n"
# 96 "data/text/battle_labyrinth.pory"
	.string "regiment you would like.$"
# 97 "data/text/battle_labyrinth.pory"

# 98 "data/text/battle_labyrinth.pory"
gText_Lelouch_CostsBlueShards:
# 99 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Move Reminder services\n"
# 100 "data/text/battle_labyrinth.pory"
	.string "cost one Blue Shard.\p"
# 101 "data/text/battle_labyrinth.pory"
	.string "Would you like me to teach a\n"
# 102 "data/text/battle_labyrinth.pory"
	.string "forgotten move to your Pokémon?$"
# 103 "data/text/battle_labyrinth.pory"

# 104 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayBlue:
# 105 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Blue Shard.$"
# 106 "data/text/battle_labyrinth.pory"

# 107 "data/text/battle_labyrinth.pory"
gText_Lelouch_CostsYellowShards:
# 108 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Move Tutor services cost\n"
# 109 "data/text/battle_labyrinth.pory"
	.string "Yellow Shards. Which move would you\l"
# 110 "data/text/battle_labyrinth.pory"
	.string "like to tutor?$"
# 111 "data/text/battle_labyrinth.pory"

# 112 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayYellow1:
# 113 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Yellow Shard.$"
# 114 "data/text/battle_labyrinth.pory"

# 115 "data/text/battle_labyrinth.pory"
gText_Lelouch_CostsGreenShards:
# 116 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: I can craft special items\n"
# 117 "data/text/battle_labyrinth.pory"
	.string "as well as upgrade your items\l"
# 118 "data/text/battle_labyrinth.pory"
	.string "in exchange for Green Shards.\l"
# 119 "data/text/battle_labyrinth.pory"
	.string "What would you like?$"
# 120 "data/text/battle_labyrinth.pory"

# 121 "data/text/battle_labyrinth.pory"
gText_Lelouch_PayGreen:
# 122 "data/text/battle_labyrinth.pory"
	.string "{PLAYER} handed over 1 Green Shard.$"
# 123 "data/text/battle_labyrinth.pory"

# 124 "data/text/battle_labyrinth.pory"
gText_HealingSign:
# 125 "data/text/battle_labyrinth.pory"
	.string "Joy's Healing Shop\n"
# 126 "data/text/battle_labyrinth.pory"
	.string "Health care costs money!$"
# 127 "data/text/battle_labyrinth.pory"

# 128 "data/text/battle_labyrinth.pory"
gText_ExitSign:
# 129 "data/text/battle_labyrinth.pory"
	.string "This is the exit!$"
# 130 "data/text/battle_labyrinth.pory"

# 131 "data/text/battle_labyrinth.pory"
gText_NotEnoughMons:
# 132 "data/text/battle_labyrinth.pory"
	.string "You need at least two Pokémon to\n"
# 133 "data/text/battle_labyrinth.pory"
	.string "initiate a Double Battle.$"
# 134 "data/text/battle_labyrinth.pory"

# 135 "data/text/battle_labyrinth.pory"
gText_PleasePick3Mons:
# 136 "data/text/battle_labyrinth.pory"
	.string "Please select three Pokémon to\n"
# 137 "data/text/battle_labyrinth.pory"
	.string "participate in the tag battle.$"

gText_Colress_EndofDemo::
# 1 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: This is the end of the demo.\n"
	.string "Our engineers are still working on the\l"
	.string "remainder of the {COLOR RED}Pokémon Battle\l"
	.string "Labyrinth{COLOR DARK_GRAY}. Please save your game using\l"
	.string "the in game save so you might be able to\l"
	.string "transfer your save file to the next\l"
	.string "version when it comes out.$"

gText_Colress_ReachedZone::
# 5 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: Congratulations.\n"
	.string "You have cleared {COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY}.$"

gText_RewardClear::
# 9 "data/text/battle_labyrinth.pory"
	.string "Your reward for clearing\n"
	.string "{COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY} is…$"

gText_Colress_WhenUReady::
# 13 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: When you are prepared to enter\n"
	.string "{COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY}, come speak to me.$"

gText_Colress_Greetings::
# 17 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: Greetings, {PLAYER}.\p"
	.string "What can I help you with?$"

gText_Colress_SureReadyToLeave::
# 21 "data/text/battle_labyrinth.pory"
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: Are you sure you're ready? You\n"
	.string "will be entering {COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY}.$"

gText_Colress_Upgraded::
# 25 "data/text/battle_labyrinth.pory"
	.string "Because of your progress, the following\n"
	.string "shops are upgraded:$"

gText_Colress_UpgradedPokeball::
# 29 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Tim's Pokéball Shop{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedPotions::
# 33 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Portentia's Potions{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedItems::
# 37 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Varrick's Extravagant Emporium{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedBerries::
# 41 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Julia's Berries{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedEggs::
# 45 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Marie's Egg Delivery Service{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedServices::
# 49 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Lelouch's Services Shop{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedRecovery::
# 53 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Joy's Center of Restoration{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedGeneral::
# 58 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Tim's Pokéball Shop{COLOR DARK_GRAY}!$"

gText_Colress_UpgradedUnique::
# 63 "data/text/battle_labyrinth.pory"
	.string "{COLOR RED}Tim's Pokéball Shop{COLOR DARK_GRAY}!$"
