gText_Birch_Welcome::
	.string "Hello there, trainer!\p"
	.string "My name is {COLOR BLUE}Dr. Colress{COLOR DARK_GRAY} of Unova.\p"
	.string "I've dedicated my life to\n"
	.string "understanding what it is that makes\l"
	.string "Pokémon Trainers powerful.\p"
	.string "In order to do so, I've created a\n"
	.string "state of the art, powerful,\l"
	.string "technological marvel.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "I've designed a simulated\n"
	.string "environment for trainers at the\l"
	.string "highest skill level, called\l"
	.string "{COLOR RED}Pokémon Battle Labyrinth{COLOR DARK_GRAY}!\p"
	.string "This simulation is meant to analyze\n"
	.string "the will, resourcefulness, and\l"
	.string "courage of all who participate.\p"
	.string "You have been specifically selected\n"
	.string "for this grand opportunity because\l"
	.string "of your experience and renown.\p"
	.string "Before you begin, I need some\n"
	.string "registration information from you.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "It will be confidential.$"

gText_Birch_BoyOrGirl::
	.string "Please select your avatar.$"

gText_Birch_WhatsYourName::
	.string "Please enter your name.$"

gText_Birch_SoItsPlayer::
	.string "Your name is {COLOR BLUE}{PLAYER}{KUN}{COLOR DARK_GRAY}?$"

gText_Birch_YourePlayer::
	.string "Thank you very much, {COLOR BLUE}{PLAYER}{KUN}{COLOR DARK_GRAY}.\n"
	.string "Your info has been saved.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "I hope you enjoy\n"
	.string "{COLOR RED}Pokémon Battle Labyrinth{COLOR DARK_GRAY}.\p"
	.string "I'll see you again soon.\p"
	.string "$"
