Zone9H_MapScripts::
	.byte 0


# 3 "data/maps/Zone9H/scripts.pory"

# 4 "data/maps/Zone9H/scripts.pory"
Zone9H_EventScript_DeveloperEatthepear::
# 5 "data/maps/Zone9H/scripts.pory"
	lock
# 6 "data/maps/Zone9H/scripts.pory"
	faceplayer
# 7 "data/maps/Zone9H/scripts.pory"
	msgbox Zone9H_Text_Eatthepear, MSGBOX_AUTOCLOSE
# 8 "data/maps/Zone9H/scripts.pory"
	release
# 9 "data/maps/Zone9H/scripts.pory"
	end
# 10 "data/maps/Zone9H/scripts.pory"

# 11 "data/maps/Zone9H/scripts.pory"
Zone9H_Text_Eatthepear:
# 12 "data/maps/Zone9H/scripts.pory"
	.string "Hello there! It's {COLOR BLUE}eatthepear{COLOR DARK_GRAY}, the\n"
# 13 "data/maps/Zone9H/scripts.pory"
	.string "developer of this ROM hack!\p"
# 14 "data/maps/Zone9H/scripts.pory"
	.string "Thanks for playing and I hope\n"
# 15 "data/maps/Zone9H/scripts.pory"
	.string "you're enjoying your time.\p"
# 16 "data/maps/Zone9H/scripts.pory"
	.string "When you beat the game, come back\n"
# 17 "data/maps/Zone9H/scripts.pory"
	.string "here and let's have a battle!$"
