Zone9B_MapScripts::
	.byte 0


Zone9B_EventScript_Woman::
# 4 "data/maps/Zone9B/scripts.pory"
	lock
# 5 "data/maps/Zone9B/scripts.pory"
	faceplayer
# 6 "data/maps/Zone9B/scripts.pory"
	msgbox Zone9B_EventScript_Woman_Text_0
# 7 "data/maps/Zone9B/scripts.pory"
	release
	end


Zone9B_EventScript_Woman_Text_0:
# 6 "data/maps/Zone9B/scripts.pory"
	.string "In the Sinnoh region, where I'm from, we\n"
	.string "give Gracidea flowers as a gesture of\l"
	.string "gratitude.$"
