# 1 "data//scripts/movement.pory"

# 2 "data//scripts/movement.pory"
@ Starting from here, these movements are considered
# 3 "data//scripts/movement.pory"
@ 'safe' (won't put follower into a Pokeball)
# 4 "data//scripts/movement.pory"
Common_Movement_FollowerSafeStart::
# 5 "data//scripts/movement.pory"
Common_Movement_QuestionMark::
# 6 "data//scripts/movement.pory"
	emote_question_mark
# 7 "data//scripts/movement.pory"
	step_end
# 8 "data//scripts/movement.pory"

# 9 "data//scripts/movement.pory"
Common_Movement_ExclamationMark::
# 10 "data//scripts/movement.pory"
	emote_exclamation_mark
# 11 "data//scripts/movement.pory"
	step_end
# 12 "data//scripts/movement.pory"

# 13 "data//scripts/movement.pory"
Common_Movement_Delay48::
# 14 "data//scripts/movement.pory"
	delay_16
# 15 "data//scripts/movement.pory"
	delay_16
# 16 "data//scripts/movement.pory"
	delay_16
# 17 "data//scripts/movement.pory"
	step_end
# 18 "data//scripts/movement.pory"

# 19 "data//scripts/movement.pory"
Common_Movement_FacePlayer::
# 20 "data//scripts/movement.pory"
	face_player
# 21 "data//scripts/movement.pory"
	step_end
# 22 "data//scripts/movement.pory"

# 23 "data//scripts/movement.pory"
Common_Movement_FaceAwayPlayer::
# 24 "data//scripts/movement.pory"
	face_away_player
# 25 "data//scripts/movement.pory"
	step_end
# 26 "data//scripts/movement.pory"

# 27 "data//scripts/movement.pory"
Common_Movement_FaceOriginalDirection::
# 28 "data//scripts/movement.pory"
	face_original_direction
# 29 "data//scripts/movement.pory"
	step_end
# 30 "data//scripts/movement.pory"

# 31 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceFasterLeft::
# 32 "data//scripts/movement.pory"
	walk_in_place_faster_left
# 33 "data//scripts/movement.pory"
	step_end
# 34 "data//scripts/movement.pory"

# 35 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceFasterUp::
# 36 "data//scripts/movement.pory"
	walk_in_place_faster_up
# 37 "data//scripts/movement.pory"
	step_end
# 38 "data//scripts/movement.pory"

# 39 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceFasterRight::
# 40 "data//scripts/movement.pory"
	walk_in_place_faster_right
# 41 "data//scripts/movement.pory"
	step_end
# 42 "data//scripts/movement.pory"

# 43 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceFasterDown::
# 44 "data//scripts/movement.pory"
	walk_in_place_faster_down
# 45 "data//scripts/movement.pory"
	step_end
# 46 "data//scripts/movement.pory"

# 47 "data//scripts/movement.pory"
Common_Movement_FaceRight::
# 48 "data//scripts/movement.pory"
	face_right
# 49 "data//scripts/movement.pory"
	step_end
# 50 "data//scripts/movement.pory"

# 51 "data//scripts/movement.pory"
Common_Movement_FaceLeft::
# 52 "data//scripts/movement.pory"
	face_left
# 53 "data//scripts/movement.pory"
	step_end
# 54 "data//scripts/movement.pory"

# 55 "data//scripts/movement.pory"
Common_Movement_FaceDown::
# 56 "data//scripts/movement.pory"
	face_down
# 57 "data//scripts/movement.pory"
	step_end
# 58 "data//scripts/movement.pory"

# 59 "data//scripts/movement.pory"
Common_Movement_FaceUp::
# 60 "data//scripts/movement.pory"
	face_up
# 61 "data//scripts/movement.pory"
	step_end
# 62 "data//scripts/movement.pory"

# 63 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceDown::
# 64 "data//scripts/movement.pory"
	walk_in_place_down
# 65 "data//scripts/movement.pory"
	step_end
# 66 "data//scripts/movement.pory"

# 67 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceLeft::
# 68 "data//scripts/movement.pory"
	walk_in_place_left
# 69 "data//scripts/movement.pory"
	step_end
# 70 "data//scripts/movement.pory"

# 71 "data//scripts/movement.pory"
Common_Movement_WalkInPlaceRight::
# 72 "data//scripts/movement.pory"
	walk_in_place_right
# 73 "data//scripts/movement.pory"
	step_end
# 74 "data//scripts/movement.pory"

# 75 "data//scripts/movement.pory"
@ End of follower-safe movements
# 76 "data//scripts/movement.pory"
Common_Movement_FollowerSafeEnd::
# 77 "data//scripts/movement.pory"
	step_end

# 80 "data//scripts/movement.pory"
Common_Movement_WalkUp:
# 81 "data//scripts/movement.pory"
	walk_up
	step_end

# 84 "data//scripts/movement.pory"
Common_Movement_WalkDown:
# 85 "data//scripts/movement.pory"
	walk_down
	step_end

# 88 "data//scripts/movement.pory"
Common_Movement_WalkLeft:
# 89 "data//scripts/movement.pory"
	walk_left
	step_end

# 92 "data//scripts/movement.pory"
Common_Movement_WalkRight:
# 93 "data//scripts/movement.pory"
	walk_right
	step_end

# 96 "data//scripts/movement.pory"
Common_Movement_Delay32:
# 97 "data//scripts/movement.pory"
	delay_16
# 97 "data//scripts/movement.pory"
	delay_16
	step_end

# 100 "data//scripts/movement.pory"
Common_Movement_WalkUp2:
# 101 "data//scripts/movement.pory"
	walk_up
# 101 "data//scripts/movement.pory"
	walk_up
	step_end

# 104 "data//scripts/movement.pory"
Common_Movement_WalkDown2:
# 105 "data//scripts/movement.pory"
	walk_down
# 105 "data//scripts/movement.pory"
	walk_down
	step_end

# 108 "data//scripts/movement.pory"
Common_Movement_WalkLeft2:
# 109 "data//scripts/movement.pory"
	walk_left
# 109 "data//scripts/movement.pory"
	walk_left
	step_end

# 112 "data//scripts/movement.pory"
Common_Movement_WalkRight2:
# 113 "data//scripts/movement.pory"
	walk_right
# 113 "data//scripts/movement.pory"
	walk_right
	step_end

# 116 "data//scripts/movement.pory"
Common_Movement_WalkUp3:
# 117 "data//scripts/movement.pory"
	walk_up
# 117 "data//scripts/movement.pory"
	walk_up
# 117 "data//scripts/movement.pory"
	walk_up
	step_end

# 120 "data//scripts/movement.pory"
Common_Movement_WalkDown3:
# 121 "data//scripts/movement.pory"
	walk_down
# 121 "data//scripts/movement.pory"
	walk_down
# 121 "data//scripts/movement.pory"
	walk_down
	step_end

# 124 "data//scripts/movement.pory"
Common_Movement_WalkLeft3:
# 125 "data//scripts/movement.pory"
	walk_left
# 125 "data//scripts/movement.pory"
	walk_left
# 125 "data//scripts/movement.pory"
	walk_left
	step_end

# 128 "data//scripts/movement.pory"
Common_Movement_WalkRight3:
# 129 "data//scripts/movement.pory"
	walk_right
# 129 "data//scripts/movement.pory"
	walk_right
# 129 "data//scripts/movement.pory"
	walk_right
	step_end

# 132 "data//scripts/movement.pory"
Common_Movement_WalkUp4:
# 133 "data//scripts/movement.pory"
	walk_up
# 133 "data//scripts/movement.pory"
	walk_up
# 133 "data//scripts/movement.pory"
	walk_up
# 133 "data//scripts/movement.pory"
	walk_up
	step_end

# 136 "data//scripts/movement.pory"
Common_Movement_WalkDown4:
# 137 "data//scripts/movement.pory"
	walk_down
# 137 "data//scripts/movement.pory"
	walk_down
# 137 "data//scripts/movement.pory"
	walk_down
# 137 "data//scripts/movement.pory"
	walk_down
	step_end

# 140 "data//scripts/movement.pory"
Common_Movement_WalkLeft4:
# 141 "data//scripts/movement.pory"
	walk_left
# 141 "data//scripts/movement.pory"
	walk_left
# 141 "data//scripts/movement.pory"
	walk_left
# 141 "data//scripts/movement.pory"
	walk_left
	step_end

# 144 "data//scripts/movement.pory"
Common_Movement_WalkRight4:
# 145 "data//scripts/movement.pory"
	walk_right
# 145 "data//scripts/movement.pory"
	walk_right
# 145 "data//scripts/movement.pory"
	walk_right
# 145 "data//scripts/movement.pory"
	walk_right
	step_end

# 148 "data//scripts/movement.pory"
Common_Movement_WalkUp5:
# 149 "data//scripts/movement.pory"
	walk_up
# 149 "data//scripts/movement.pory"
	walk_up
# 149 "data//scripts/movement.pory"
	walk_up
# 149 "data//scripts/movement.pory"
	walk_up
# 149 "data//scripts/movement.pory"
	walk_up
	step_end

# 152 "data//scripts/movement.pory"
Common_Movement_WalkDown5:
# 153 "data//scripts/movement.pory"
	walk_down
# 153 "data//scripts/movement.pory"
	walk_down
# 153 "data//scripts/movement.pory"
	walk_down
# 153 "data//scripts/movement.pory"
	walk_down
# 153 "data//scripts/movement.pory"
	walk_down
	step_end

# 156 "data//scripts/movement.pory"
Common_Movement_WalkLeft5:
# 157 "data//scripts/movement.pory"
	walk_left
# 157 "data//scripts/movement.pory"
	walk_left
# 157 "data//scripts/movement.pory"
	walk_left
# 157 "data//scripts/movement.pory"
	walk_left
# 157 "data//scripts/movement.pory"
	walk_left
	step_end

# 160 "data//scripts/movement.pory"
Common_Movement_WalkRight5:
# 161 "data//scripts/movement.pory"
	walk_right
# 161 "data//scripts/movement.pory"
	walk_right
# 161 "data//scripts/movement.pory"
	walk_right
# 161 "data//scripts/movement.pory"
	walk_right
# 161 "data//scripts/movement.pory"
	walk_right
	step_end

# 164 "data//scripts/movement.pory"
Common_Movement_WalkUp6:
# 165 "data//scripts/movement.pory"
	walk_up
# 165 "data//scripts/movement.pory"
	walk_up
# 165 "data//scripts/movement.pory"
	walk_up
# 165 "data//scripts/movement.pory"
	walk_up
# 165 "data//scripts/movement.pory"
	walk_up
# 165 "data//scripts/movement.pory"
	walk_up
	step_end

# 168 "data//scripts/movement.pory"
Common_Movement_WalkDown6:
# 169 "data//scripts/movement.pory"
	walk_down
# 169 "data//scripts/movement.pory"
	walk_down
# 169 "data//scripts/movement.pory"
	walk_down
# 169 "data//scripts/movement.pory"
	walk_down
# 169 "data//scripts/movement.pory"
	walk_down
# 169 "data//scripts/movement.pory"
	walk_down
	step_end

# 172 "data//scripts/movement.pory"
Common_Movement_WalkLeft6:
# 173 "data//scripts/movement.pory"
	walk_left
# 173 "data//scripts/movement.pory"
	walk_left
# 173 "data//scripts/movement.pory"
	walk_left
# 173 "data//scripts/movement.pory"
	walk_left
# 173 "data//scripts/movement.pory"
	walk_left
# 173 "data//scripts/movement.pory"
	walk_left
	step_end

# 176 "data//scripts/movement.pory"
Common_Movement_WalkRight6:
# 177 "data//scripts/movement.pory"
	walk_right
# 177 "data//scripts/movement.pory"
	walk_right
# 177 "data//scripts/movement.pory"
	walk_right
# 177 "data//scripts/movement.pory"
	walk_right
# 177 "data//scripts/movement.pory"
	walk_right
# 177 "data//scripts/movement.pory"
	walk_right
	step_end

# 180 "data//scripts/movement.pory"
Common_Movement_Colress_WalkDown:
# 181 "data//scripts/movement.pory"
	walk_down
# 181 "data//scripts/movement.pory"
	walk_down
# 181 "data//scripts/movement.pory"
	walk_down
	step_end

# 184 "data//scripts/movement.pory"
Common_Movement_Colress_WalkUp:
# 185 "data//scripts/movement.pory"
	walk_up
# 185 "data//scripts/movement.pory"
	walk_up
# 185 "data//scripts/movement.pory"
	walk_up
# 186 "data//scripts/movement.pory"
	face_down
	step_end
