# 1 "data/scripts/movement.pory"

# 2 "data/scripts/movement.pory"
@ Starting from here, these movements are considered
# 3 "data/scripts/movement.pory"
@ 'safe' (won't put follower into a Pokeball)
# 4 "data/scripts/movement.pory"
Common_Movement_FollowerSafeStart::

# 7 "data/scripts/movement.pory"
Common_Movement_QuestionMark:
# 8 "data/scripts/movement.pory"
	emote_question_mark
	step_end

# 11 "data/scripts/movement.pory"
Common_Movement_ExclamationMark:
# 12 "data/scripts/movement.pory"
	emote_exclamation_mark
	step_end

# 15 "data/scripts/movement.pory"
Common_Movement_Delay48:
# 16 "data/scripts/movement.pory"
	delay_16
# 16 "data/scripts/movement.pory"
	delay_16
# 16 "data/scripts/movement.pory"
	delay_16
	step_end

# 19 "data/scripts/movement.pory"
Common_Movement_FacePlayer:
# 20 "data/scripts/movement.pory"
	face_player
	step_end

# 23 "data/scripts/movement.pory"
Common_Movement_FaceAwayPlayer:
# 24 "data/scripts/movement.pory"
	face_away_player
	step_end

# 27 "data/scripts/movement.pory"
Common_Movement_FaceOriginalDirection:
# 28 "data/scripts/movement.pory"
	face_original_direction
	step_end

# 31 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterLeft:
# 32 "data/scripts/movement.pory"
	walk_in_place_faster_left
	step_end

# 35 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterUp:
# 36 "data/scripts/movement.pory"
	walk_in_place_faster_up
	step_end

# 39 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterRight:
# 40 "data/scripts/movement.pory"
	walk_in_place_faster_right
	step_end

# 43 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterDown:
# 44 "data/scripts/movement.pory"
	walk_in_place_faster_down
	step_end

# 47 "data/scripts/movement.pory"
Common_Movement_FaceRight:
# 48 "data/scripts/movement.pory"
	face_right
	step_end

# 51 "data/scripts/movement.pory"
Common_Movement_FaceLeft:
# 52 "data/scripts/movement.pory"
	face_left
	step_end

# 55 "data/scripts/movement.pory"
Common_Movement_FaceDown:
# 56 "data/scripts/movement.pory"
	face_down
	step_end

# 59 "data/scripts/movement.pory"
Common_Movement_FaceUp:
# 60 "data/scripts/movement.pory"
	face_up
	step_end

# 63 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceDown:
# 64 "data/scripts/movement.pory"
	walk_in_place_down
	step_end

# 67 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceLeft:
# 68 "data/scripts/movement.pory"
	walk_in_place_left
	step_end

# 71 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceRight:
# 72 "data/scripts/movement.pory"
	walk_in_place_right
	step_end

# 75 "data/scripts/movement.pory"

# 76 "data/scripts/movement.pory"
@ End of follower-safe movements
# 77 "data/scripts/movement.pory"
Common_Movement_FollowerSafeEnd::
# 78 "data/scripts/movement.pory"
	step_end

# 81 "data/scripts/movement.pory"
Common_Movement_WalkUp:
# 82 "data/scripts/movement.pory"
	walk_up
	step_end

# 85 "data/scripts/movement.pory"
Common_Movement_WalkDown:
# 86 "data/scripts/movement.pory"
	walk_down
	step_end

# 89 "data/scripts/movement.pory"
Common_Movement_WalkLeft:
# 90 "data/scripts/movement.pory"
	walk_left
	step_end

# 93 "data/scripts/movement.pory"
Common_Movement_WalkRight:
# 94 "data/scripts/movement.pory"
	walk_right
	step_end

# 97 "data/scripts/movement.pory"
Common_Movement_Delay32:
# 98 "data/scripts/movement.pory"
	delay_16
# 98 "data/scripts/movement.pory"
	delay_16
	step_end

# 101 "data/scripts/movement.pory"
Common_Movement_WalkUp2:
# 102 "data/scripts/movement.pory"
	walk_up
# 102 "data/scripts/movement.pory"
	walk_up
	step_end

# 105 "data/scripts/movement.pory"
Common_Movement_WalkDown2:
# 106 "data/scripts/movement.pory"
	walk_down
# 106 "data/scripts/movement.pory"
	walk_down
	step_end

# 109 "data/scripts/movement.pory"
Common_Movement_WalkLeft2:
# 110 "data/scripts/movement.pory"
	walk_left
# 110 "data/scripts/movement.pory"
	walk_left
	step_end

# 113 "data/scripts/movement.pory"
Common_Movement_WalkRight2:
# 114 "data/scripts/movement.pory"
	walk_right
# 114 "data/scripts/movement.pory"
	walk_right
	step_end

# 117 "data/scripts/movement.pory"
Common_Movement_WalkUp3:
# 118 "data/scripts/movement.pory"
	walk_up
# 118 "data/scripts/movement.pory"
	walk_up
# 118 "data/scripts/movement.pory"
	walk_up
	step_end

# 121 "data/scripts/movement.pory"
Common_Movement_WalkDown3:
# 122 "data/scripts/movement.pory"
	walk_down
# 122 "data/scripts/movement.pory"
	walk_down
# 122 "data/scripts/movement.pory"
	walk_down
	step_end

# 125 "data/scripts/movement.pory"
Common_Movement_WalkLeft3:
# 126 "data/scripts/movement.pory"
	walk_left
# 126 "data/scripts/movement.pory"
	walk_left
# 126 "data/scripts/movement.pory"
	walk_left
	step_end

# 129 "data/scripts/movement.pory"
Common_Movement_WalkRight3:
# 130 "data/scripts/movement.pory"
	walk_right
# 130 "data/scripts/movement.pory"
	walk_right
# 130 "data/scripts/movement.pory"
	walk_right
	step_end

# 133 "data/scripts/movement.pory"
Common_Movement_WalkUp4:
# 134 "data/scripts/movement.pory"
	walk_up
# 134 "data/scripts/movement.pory"
	walk_up
# 134 "data/scripts/movement.pory"
	walk_up
# 134 "data/scripts/movement.pory"
	walk_up
	step_end

# 137 "data/scripts/movement.pory"
Common_Movement_WalkDown4:
# 138 "data/scripts/movement.pory"
	walk_down
# 138 "data/scripts/movement.pory"
	walk_down
# 138 "data/scripts/movement.pory"
	walk_down
# 138 "data/scripts/movement.pory"
	walk_down
	step_end

# 141 "data/scripts/movement.pory"
Common_Movement_WalkLeft4:
# 142 "data/scripts/movement.pory"
	walk_left
# 142 "data/scripts/movement.pory"
	walk_left
# 142 "data/scripts/movement.pory"
	walk_left
# 142 "data/scripts/movement.pory"
	walk_left
	step_end

# 145 "data/scripts/movement.pory"
Common_Movement_WalkRight4:
# 146 "data/scripts/movement.pory"
	walk_right
# 146 "data/scripts/movement.pory"
	walk_right
# 146 "data/scripts/movement.pory"
	walk_right
# 146 "data/scripts/movement.pory"
	walk_right
	step_end

# 149 "data/scripts/movement.pory"
Common_Movement_WalkUp5:
# 150 "data/scripts/movement.pory"
	walk_up
# 150 "data/scripts/movement.pory"
	walk_up
# 150 "data/scripts/movement.pory"
	walk_up
# 150 "data/scripts/movement.pory"
	walk_up
# 150 "data/scripts/movement.pory"
	walk_up
	step_end

# 153 "data/scripts/movement.pory"
Common_Movement_WalkDown5:
# 154 "data/scripts/movement.pory"
	walk_down
# 154 "data/scripts/movement.pory"
	walk_down
# 154 "data/scripts/movement.pory"
	walk_down
# 154 "data/scripts/movement.pory"
	walk_down
# 154 "data/scripts/movement.pory"
	walk_down
	step_end

# 157 "data/scripts/movement.pory"
Common_Movement_WalkLeft5:
# 158 "data/scripts/movement.pory"
	walk_left
# 158 "data/scripts/movement.pory"
	walk_left
# 158 "data/scripts/movement.pory"
	walk_left
# 158 "data/scripts/movement.pory"
	walk_left
# 158 "data/scripts/movement.pory"
	walk_left
	step_end

# 161 "data/scripts/movement.pory"
Common_Movement_WalkRight5:
# 162 "data/scripts/movement.pory"
	walk_right
# 162 "data/scripts/movement.pory"
	walk_right
# 162 "data/scripts/movement.pory"
	walk_right
# 162 "data/scripts/movement.pory"
	walk_right
# 162 "data/scripts/movement.pory"
	walk_right
	step_end

# 165 "data/scripts/movement.pory"
Common_Movement_WalkUp6:
# 166 "data/scripts/movement.pory"
	walk_up
# 166 "data/scripts/movement.pory"
	walk_up
# 166 "data/scripts/movement.pory"
	walk_up
# 166 "data/scripts/movement.pory"
	walk_up
# 166 "data/scripts/movement.pory"
	walk_up
# 166 "data/scripts/movement.pory"
	walk_up
	step_end

# 169 "data/scripts/movement.pory"
Common_Movement_WalkDown6:
# 170 "data/scripts/movement.pory"
	walk_down
# 170 "data/scripts/movement.pory"
	walk_down
# 170 "data/scripts/movement.pory"
	walk_down
# 170 "data/scripts/movement.pory"
	walk_down
# 170 "data/scripts/movement.pory"
	walk_down
# 170 "data/scripts/movement.pory"
	walk_down
	step_end

# 173 "data/scripts/movement.pory"
Common_Movement_WalkLeft6:
# 174 "data/scripts/movement.pory"
	walk_left
# 174 "data/scripts/movement.pory"
	walk_left
# 174 "data/scripts/movement.pory"
	walk_left
# 174 "data/scripts/movement.pory"
	walk_left
# 174 "data/scripts/movement.pory"
	walk_left
# 174 "data/scripts/movement.pory"
	walk_left
	step_end

# 177 "data/scripts/movement.pory"
Common_Movement_WalkRight6:
# 178 "data/scripts/movement.pory"
	walk_right
# 178 "data/scripts/movement.pory"
	walk_right
# 178 "data/scripts/movement.pory"
	walk_right
# 178 "data/scripts/movement.pory"
	walk_right
# 178 "data/scripts/movement.pory"
	walk_right
# 178 "data/scripts/movement.pory"
	walk_right
	step_end

# 181 "data/scripts/movement.pory"
Common_Movement_Colress_WalkDown:
# 182 "data/scripts/movement.pory"
	walk_down
# 182 "data/scripts/movement.pory"
	walk_down
# 182 "data/scripts/movement.pory"
	walk_down
	step_end

# 185 "data/scripts/movement.pory"
Common_Movement_Colress_WalkUp:
# 186 "data/scripts/movement.pory"
	walk_up
# 186 "data/scripts/movement.pory"
	walk_up
# 186 "data/scripts/movement.pory"
	walk_up
# 187 "data/scripts/movement.pory"
	face_down
	step_end
