# 1 "data/scripts/movement.pory"
Common_Movement_QuestionMark:
# 2 "data/scripts/movement.pory"
	emote_question_mark
	step_end

# 5 "data/scripts/movement.pory"
Common_Movement_ExclamationMark:
# 6 "data/scripts/movement.pory"
	emote_exclamation_mark
	step_end

# 9 "data/scripts/movement.pory"
Common_Movement_Delay48:
# 10 "data/scripts/movement.pory"
	delay_16
# 10 "data/scripts/movement.pory"
	delay_16
# 10 "data/scripts/movement.pory"
	delay_16
	step_end

# 13 "data/scripts/movement.pory"
Common_Movement_FacePlayer:
# 14 "data/scripts/movement.pory"
	face_player
	step_end

# 17 "data/scripts/movement.pory"
Common_Movement_FaceAwayPlayer:
# 18 "data/scripts/movement.pory"
	face_away_player
	step_end

# 21 "data/scripts/movement.pory"
Common_Movement_FaceOriginalDirection:
# 22 "data/scripts/movement.pory"
	face_original_direction
	step_end

# 25 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterLeft:
# 26 "data/scripts/movement.pory"
	walk_in_place_faster_left
	step_end

# 29 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterUp:
# 30 "data/scripts/movement.pory"
	walk_in_place_faster_up
	step_end

# 33 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterRight:
# 34 "data/scripts/movement.pory"
	walk_in_place_faster_right
	step_end

# 37 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceFasterDown:
# 38 "data/scripts/movement.pory"
	walk_in_place_faster_down
	step_end

# 41 "data/scripts/movement.pory"
Common_Movement_FaceRight:
# 42 "data/scripts/movement.pory"
	face_right
	step_end

# 45 "data/scripts/movement.pory"
Common_Movement_FaceLeft:
# 46 "data/scripts/movement.pory"
	face_left
	step_end

# 49 "data/scripts/movement.pory"
Common_Movement_FaceDown:
# 50 "data/scripts/movement.pory"
	face_down
	step_end

# 53 "data/scripts/movement.pory"
Common_Movement_FaceUp:
# 54 "data/scripts/movement.pory"
	face_up
	step_end

# 57 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceDown:
# 58 "data/scripts/movement.pory"
	walk_in_place_down
	step_end

# 61 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceLeft:
# 62 "data/scripts/movement.pory"
	walk_in_place_left
	step_end

# 65 "data/scripts/movement.pory"
Common_Movement_WalkInPlaceRight:
# 66 "data/scripts/movement.pory"
	walk_in_place_right
	step_end

# 69 "data/scripts/movement.pory"
Common_Movement_WalkUp6:
# 70 "data/scripts/movement.pory"
	walk_up
# 70 "data/scripts/movement.pory"
	walk_up
# 70 "data/scripts/movement.pory"
	walk_up
# 70 "data/scripts/movement.pory"
	walk_up
# 70 "data/scripts/movement.pory"
	walk_up
# 70 "data/scripts/movement.pory"
	walk_up
	step_end

# 73 "data/scripts/movement.pory"
Common_Movement_WalkUp4:
# 74 "data/scripts/movement.pory"
	walk_up
# 74 "data/scripts/movement.pory"
	walk_up
# 74 "data/scripts/movement.pory"
	walk_up
# 74 "data/scripts/movement.pory"
	walk_up
	step_end

# 77 "data/scripts/movement.pory"
Common_Movement_Delay32:
# 78 "data/scripts/movement.pory"
	delay_16
# 78 "data/scripts/movement.pory"
	delay_16
	step_end

# 81 "data/scripts/movement.pory"
Common_Movement_WalkUp:
# 82 "data/scripts/movement.pory"
	walk_up
	step_end

# 85 "data/scripts/movement.pory"
Common_Movement_WalkDown:
# 86 "data/scripts/movement.pory"
	walk_down
	step_end

# 89 "data/scripts/movement.pory"
Common_Movement_WalkLeft:
# 90 "data/scripts/movement.pory"
	walk_left
	step_end

# 93 "data/scripts/movement.pory"
Common_Movement_WalkRight:
# 94 "data/scripts/movement.pory"
	walk_right
	step_end

# 97 "data/scripts/movement.pory"
Common_Movement_WalkUp2:
# 98 "data/scripts/movement.pory"
	walk_up
# 98 "data/scripts/movement.pory"
	walk_up
	step_end

# 101 "data/scripts/movement.pory"
Common_Movement_Colress_WalkDown:
# 102 "data/scripts/movement.pory"
	walk_down
# 102 "data/scripts/movement.pory"
	walk_down
	step_end

# 105 "data/scripts/movement.pory"
Common_Movement_Colress_WalkUp:
# 106 "data/scripts/movement.pory"
	walk_up
# 106 "data/scripts/movement.pory"
	walk_up
# 107 "data/scripts/movement.pory"
	face_down
	step_end
