ZoneSanctuary_PeacefulGrove_MapScripts::
	.byte 0


ZoneSanctuary_PeacefulGrove_EventScript_Pokemaniac::
# 4 "data/maps/ZoneSanctuary_PeacefulGrove/scripts.pory"
	lock
# 5 "data/maps/ZoneSanctuary_PeacefulGrove/scripts.pory"
	faceplayer
# 6 "data/maps/ZoneSanctuary_PeacefulGrove/scripts.pory"
	msgbox ZoneSanctuary_PeacefulGrove_EventScript_Pokemaniac_Text_0
# 7 "data/maps/ZoneSanctuary_PeacefulGrove/scripts.pory"
	release
	return


ZoneSanctuary_PeacefulGrove_EventScript_Pokemaniac_Text_0:
# 6 "data/maps/ZoneSanctuary_PeacefulGrove/scripts.pory"
	.string "You're telling me I can't grind items or\n"
	.string "money? What's the point then?\p"
	.string "I guess I could switch to Easy\n"
	.string "difficulty…$"
